politics:
  name: '10'
  id: '86'
economics:
  name: '9'
  id: '39'
finance:
  name: '310'
  id: '41'
society:
  name: '11'
  id: '43'
world:
  name: '3'
  id: '49'
sports:
  name: '6'
  id: '53'
culture:
  name: '5'
  id: '57'
'42':
  name: '15'
  id: '65'
auto:
  name: '7'
  id: '69'
accidents:
  name: '103'
  id: '73'
property:
  name: '486'
  id: '79'
agenda:
  name: '491'
  id: '98'




































