start: 'Добро пожаловать в неофициальный бот лучшего интернет-портала страны TUT.BY! Чтобы узнать список команд, наберите /help'
already_subscribed: 'Вы уже подписаны на рассылку. Спасибо!'
subscription_on: 'Спасибо за подписку на нашу рассылку. Ждите новостей каждый вечер в 19:00 по Минску.'
subscription_off: 'Нам жаль, что вы решили отписаться от наших новостей. Надеемся, что вы передумаете.'
author: 'Меня создали @Chyrta и @aleks_senkou. Вы можете обращаться к нам с критикой и предложениями.'
try_search: 'Для того, чтобы найти новости по фразе, напишите команду /search и добавьте после нее слово.'
no_news_found: 'Новостей не найдено'
help: |
    Бот TUT.BY отдает по 5 новостей по запросу:
    /top — главные новости
    /now — новости, которые сейчас читают
    /politics — новости политики
    /economics — новости экономики и бизнеса
    /finance — новости финансов
    /society — новости общества
    /world — мировые новости
    /sports — новости спорта
    /culture — новости культуры
    /42 — новости из мира технологий
    /auto — новости из автомира
    /accidents — происшествия
    /property — недвижимость
    /agenda — афиша
    /subscription - вкл/выкл рассылку новостей на основании прошлых запросов
    /kurs — курс основных валют от НБРБ
    /author — информация об авторе бота
